# Override default flag values for local packages and extra-deps
flags:
  QuickFuzz:
    debug : false
    image : false
    arch : false
    doc : false
    code : false
    media : false
    pki : false
    bnfc : false
    all : false

extra-package-dbs: []

packages:
- location: https://github.com/CIFASIS/megadeth/archive/master.zip
  extra-dep: true
  
- location: https://bitbucket.org/jmg/global-variables/get/6bbea1933b8e.zip
  extra-dep: true

- location: https://github.com/agustinmista/ArgParser/archive/master.zip
  extra-dep: true

- location: https://github.com/agustinmista/GhcMod/archive/master.zip
  extra-dep: true

# Media

- location:
    git: https://bitbucket.org/robertmassaioli/riff.git
    commit: 01734c4d205c642c471fd3ba76c2d492605f39c8
  extra-dep: true

- location: https://github.com/CIFASIS/wavy/archive/master.zip
  extra-dep: true

# Code

- location: https://github.com/remyoudompheng/hs-language-go/archive/master.zip
  extra-dep: true

# PKI

- location: https://github.com/CIFASIS/hs-certificate-x509/archive/master.zip
  extra-dep: true

- location: https://github.com/CIFASIS/hs-asn1-encoding/archive/master.zip
  extra-dep: true

# Imgs

- location: https://github.com/CIFASIS/Juicy.Pixels/archive/master.zip
  extra-dep: true

- '.'

extra-deps:
- QuickCheck-2.9.2
- derive-2.5.26
- vector-0.10.12.3
- process-extras-0.4.1.4
- generic-deriving-1.10.0
- language-python-0.5.4
# - global-variables-1.0.1.0
- svg-tree-0.6
# - language-go-0.9
- easyrender-0.1.1.1
- superdoc-0.1.2.4
- bytestring-0.10.8.1
- language-css-0.0.3
- language-lua-0.10.0
- language-glsl-0.2.1
- ethereum-analyzer-deps-1.3.0
- global-lock-0.1
- BNFC-2.8.1
- tagged-0.8.6@sha256:b5e1de3b14ff198b548928f686e5e8783301dc231413f751c23f4ee10cd47a7c

explicit-setup-deps:
  ! '*': true

resolver: lts-5.9
